name: CI

on: [push]

jobs:
  push_to_registry:
    name: docker python
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/schtukaturken/noyabr:1.0 ./python-app
      
  docker_node:
    needs: [push_to_registry]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Change directory to node-app
        run: cd ./node-app
    
      - name: Install Node.js dependencies
        run: npm install node
    
      - name: docker node
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - run: docker build -t ghcr.io/schtukaturken/noyabr:1.0 ./node-app

      - run: ssh -t 'schtukaturken-noyabr-0necxe6fot1#d-pnhYut0jCfrhB5PXqh7Ai8Lt19z2mW@schtukaturken-noyabr-0necxe6fot1.ssh.ws-eu107.gitpod.io'
